#menampilkan perkenalan
nama_panggilan=("jimmy")
print("Assalamualaikum warahmatullahi wabarakatuh")
print("Perkenalkan nama saya Hilmy Muhammad Aqil")
print("Biasa dipanggil hilmy atau" ,nama_panggilan)

#menampilkan biodata
umur_tahun = int(4002 / 2)
umur_hari = int(28 + 2.5-1)
umur_bulan = int(24 / 2)
umur_saya = float(19.3)
tempat_lahir = ("bekasi")
tinggi_badan = float(178.5)
berat_badan = float(77.5)
ukuran_sepatu =float(44.5)
ukuran_celana= float(66 / 2)
kedua_ortu =("bapak dan ibu")
kelamin_kakakadik_satu =("cowok")
kelamin_kakak_kedua =("cewek")
terdiri_dari=("2 kakak dan 1 adik")
total_saudara=int(4 - 1)
total_kucing=int(3-2)

print("saya hilmy muhammad aqil, saua berumur", umur_saya, "tahun")
print("saya lahir pada tanggal ", umur_hari, "pada bulan",umur_bulan, "pada tahun", umur_tahun)
print("saua lahir di ", tempat_lahir)
print("saya mempunyai 2 orang tua yaitu ", kedua_ortu)
print("saya juga mempunyai 3 saudara kandung")
print("saudara kandung saya", terdiri_dari)
print("kakak yang pertama",kelamin_kakakadik_satu, "dan yang kedua", kelamin_kakak_kedua)
print("sedangkan adik saya", kelamin_kakakadik_satu)
print("kami hidup dalam kondisi yang alhamdulillah berkecukupan")
print("saya bahagia bisa menjadi anggota keluarga kecil ini")
